/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as DocumentsRouteImport } from "./routes/documents"
import { Route as ActivityRouteImport } from "./routes/activity"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ProjectsIndexRouteImport } from "./routes/projects.index"
import { Route as ProjectsProjectIdRouteImport } from "./routes/projects.$projectId"
import { Route as ProjectsProjectIdIndexRouteImport } from "./routes/projects.$projectId.index"
import { Route as ProjectsProjectIdTailoringRouteImport } from "./routes/projects.$projectId.tailoring"
import { Route as ProjectsProjectIdResumeRouteImport } from "./routes/projects.$projectId.resume"
import { Route as ProjectsProjectIdProfileRouteImport } from "./routes/projects.$projectId.profile"
import { Route as ProjectsProjectIdExplorerRouteImport } from "./routes/projects.$projectId.explorer"
import { Route as ProjectsProjectIdCoachRouteImport } from "./routes/projects.$projectId.coach"

const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: "/documents",
  path: "/documents",
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: "/activity",
  path: "/activity",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: "/projects/",
  path: "/projects/",
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: "/projects/$projectId",
  path: "/projects/$projectId",
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdTailoringRoute =
  ProjectsProjectIdTailoringRouteImport.update({
    id: "/tailoring",
    path: "/tailoring",
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdResumeRoute = ProjectsProjectIdResumeRouteImport.update({
  id: "/resume",
  path: "/resume",
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdProfileRoute =
  ProjectsProjectIdProfileRouteImport.update({
    id: "/profile",
    path: "/profile",
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdExplorerRoute =
  ProjectsProjectIdExplorerRouteImport.update({
    id: "/explorer",
    path: "/explorer",
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdCoachRoute = ProjectsProjectIdCoachRouteImport.update({
  id: "/coach",
  path: "/coach",
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/activity": typeof ActivityRoute
  "/documents": typeof DocumentsRoute
  "/settings": typeof SettingsRoute
  "/projects/$projectId": typeof ProjectsProjectIdRouteWithChildren
  "/projects/": typeof ProjectsIndexRoute
  "/projects/$projectId/coach": typeof ProjectsProjectIdCoachRoute
  "/projects/$projectId/explorer": typeof ProjectsProjectIdExplorerRoute
  "/projects/$projectId/profile": typeof ProjectsProjectIdProfileRoute
  "/projects/$projectId/resume": typeof ProjectsProjectIdResumeRoute
  "/projects/$projectId/tailoring": typeof ProjectsProjectIdTailoringRoute
  "/projects/$projectId/": typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/activity": typeof ActivityRoute
  "/documents": typeof DocumentsRoute
  "/settings": typeof SettingsRoute
  "/projects": typeof ProjectsIndexRoute
  "/projects/$projectId/coach": typeof ProjectsProjectIdCoachRoute
  "/projects/$projectId/explorer": typeof ProjectsProjectIdExplorerRoute
  "/projects/$projectId/profile": typeof ProjectsProjectIdProfileRoute
  "/projects/$projectId/resume": typeof ProjectsProjectIdResumeRoute
  "/projects/$projectId/tailoring": typeof ProjectsProjectIdTailoringRoute
  "/projects/$projectId": typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/activity": typeof ActivityRoute
  "/documents": typeof DocumentsRoute
  "/settings": typeof SettingsRoute
  "/projects/$projectId": typeof ProjectsProjectIdRouteWithChildren
  "/projects/": typeof ProjectsIndexRoute
  "/projects/$projectId/coach": typeof ProjectsProjectIdCoachRoute
  "/projects/$projectId/explorer": typeof ProjectsProjectIdExplorerRoute
  "/projects/$projectId/profile": typeof ProjectsProjectIdProfileRoute
  "/projects/$projectId/resume": typeof ProjectsProjectIdResumeRoute
  "/projects/$projectId/tailoring": typeof ProjectsProjectIdTailoringRoute
  "/projects/$projectId/": typeof ProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/activity"
    | "/documents"
    | "/settings"
    | "/projects/$projectId"
    | "/projects/"
    | "/projects/$projectId/coach"
    | "/projects/$projectId/explorer"
    | "/projects/$projectId/profile"
    | "/projects/$projectId/resume"
    | "/projects/$projectId/tailoring"
    | "/projects/$projectId/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/activity"
    | "/documents"
    | "/settings"
    | "/projects"
    | "/projects/$projectId/coach"
    | "/projects/$projectId/explorer"
    | "/projects/$projectId/profile"
    | "/projects/$projectId/resume"
    | "/projects/$projectId/tailoring"
    | "/projects/$projectId"
  id:
    | "__root__"
    | "/"
    | "/activity"
    | "/documents"
    | "/settings"
    | "/projects/$projectId"
    | "/projects/"
    | "/projects/$projectId/coach"
    | "/projects/$projectId/explorer"
    | "/projects/$projectId/profile"
    | "/projects/$projectId/resume"
    | "/projects/$projectId/tailoring"
    | "/projects/$projectId/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  DocumentsRoute: typeof DocumentsRoute
  SettingsRoute: typeof SettingsRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/documents": {
      id: "/documents"
      path: "/documents"
      fullPath: "/documents"
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/activity": {
      id: "/activity"
      path: "/activity"
      fullPath: "/activity"
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/projects/": {
      id: "/projects/"
      path: "/projects"
      fullPath: "/projects/"
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/projects/$projectId": {
      id: "/projects/$projectId"
      path: "/projects/$projectId"
      fullPath: "/projects/$projectId"
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/projects/$projectId/": {
      id: "/projects/$projectId/"
      path: "/"
      fullPath: "/projects/$projectId/"
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    "/projects/$projectId/tailoring": {
      id: "/projects/$projectId/tailoring"
      path: "/tailoring"
      fullPath: "/projects/$projectId/tailoring"
      preLoaderRoute: typeof ProjectsProjectIdTailoringRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    "/projects/$projectId/resume": {
      id: "/projects/$projectId/resume"
      path: "/resume"
      fullPath: "/projects/$projectId/resume"
      preLoaderRoute: typeof ProjectsProjectIdResumeRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    "/projects/$projectId/profile": {
      id: "/projects/$projectId/profile"
      path: "/profile"
      fullPath: "/projects/$projectId/profile"
      preLoaderRoute: typeof ProjectsProjectIdProfileRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    "/projects/$projectId/explorer": {
      id: "/projects/$projectId/explorer"
      path: "/explorer"
      fullPath: "/projects/$projectId/explorer"
      preLoaderRoute: typeof ProjectsProjectIdExplorerRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    "/projects/$projectId/coach": {
      id: "/projects/$projectId/coach"
      path: "/coach"
      fullPath: "/projects/$projectId/coach"
      preLoaderRoute: typeof ProjectsProjectIdCoachRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdCoachRoute: typeof ProjectsProjectIdCoachRoute
  ProjectsProjectIdExplorerRoute: typeof ProjectsProjectIdExplorerRoute
  ProjectsProjectIdProfileRoute: typeof ProjectsProjectIdProfileRoute
  ProjectsProjectIdResumeRoute: typeof ProjectsProjectIdResumeRoute
  ProjectsProjectIdTailoringRoute: typeof ProjectsProjectIdTailoringRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdCoachRoute: ProjectsProjectIdCoachRoute,
  ProjectsProjectIdExplorerRoute: ProjectsProjectIdExplorerRoute,
  ProjectsProjectIdProfileRoute: ProjectsProjectIdProfileRoute,
  ProjectsProjectIdResumeRoute: ProjectsProjectIdResumeRoute,
  ProjectsProjectIdTailoringRoute: ProjectsProjectIdTailoringRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  DocumentsRoute: DocumentsRoute,
  SettingsRoute: SettingsRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
