// Ported from browser-use (Python) chrome flag sets.
// https://github.com/browser-use/browser-use/blob/main/browser_use/browser/profile.py
// These flags suppress anti-automation fingerprints, reduce background noise,
// and keep the browser stable under aggressive CDP use.

export const CHROME_DISABLED_COMPONENTS = [
  "AcceptCHFrame",
  "AutoExpandDetailsElement",
  "AvoidUnnecessaryBeforeUnloadCheckSync",
  "CertificateTransparencyComponentUpdater",
  "DestroyProfileOnBrowserClose",
  "DialMediaRouteProvider",
  "ExtensionManifestV2Disabled",
  "GlobalMediaControls",
  "HttpsUpgrades",
  "ImprovedCookieControls",
  "LazyFrameLoading",
  "LensOverlay",
  "MediaRouter",
  "PaintHolding",
  "ThirdPartyStoragePartitioning",
  "Translate",
  "AutomationControlled",
  "BackForwardCache",
  "OptimizationHints",
  "ProcessPerSiteUpToMainFrameThreshold",
  "InterestFeedContentSuggestions",
  "CalculateNativeWinOcclusion",
  "HeavyAdPrivacyMitigations",
  "PrivacySandboxSettings4",
  "AutofillServerCommunication",
  "CrashReporting",
  "OverscrollHistoryNavigation",
  "InfiniteSessionRestore",
];

export const CHROME_HEADLESS_ARGS = ["--headless=new"];

export const CHROME_DOCKER_ARGS = [
  "--no-sandbox",
  "--disable-gpu-sandbox",
  "--disable-setuid-sandbox",
  "--disable-dev-shm-usage",
  "--no-xshm",
  "--no-zygote",
  "--disable-site-isolation-trials",
];

export const CHROME_DISABLE_SECURITY_ARGS = [
  "--disable-site-isolation-trials",
  "--disable-web-security",
  "--disable-features=IsolateOrigins,site-per-process",
  "--allow-running-insecure-content",
  "--ignore-certificate-errors",
  "--ignore-ssl-errors",
  "--ignore-certificate-errors-spki-list",
];

export const CHROME_DEFAULT_ARGS = [
  "--disable-field-trial-config",
  "--disable-background-networking",
  "--disable-background-timer-throttling",
  "--disable-backgrounding-occluded-windows",
  "--disable-back-forward-cache",
  "--disable-breakpad",
  "--disable-client-side-phishing-detection",
  "--disable-component-update",
  "--no-default-browser-check",
  "--disable-dev-shm-usage",
  "--disable-hang-monitor",
  "--disable-ipc-flooding-protection",
  "--disable-popup-blocking",
  "--disable-prompt-on-repost",
  "--disable-renderer-backgrounding",
  "--metrics-recording-only",
  "--no-first-run",
  "--no-service-autorun",
  "--export-tagged-pdf",
  "--disable-search-engine-choice-screen",
  "--unsafely-disable-devtools-self-xss-warnings",
  "--enable-features=NetworkService,NetworkServiceInProcess",
  "--enable-network-information-downlink-max",
  "--disable-sync",
  "--allow-legacy-extension-manifests",
  "--allow-pre-commit-input",
  "--disable-blink-features=AutomationControlled",
  "--install-autogenerated-theme=0,0,0",
  "--log-level=2",
  "--disable-focus-on-load",
  "--disable-window-activation",
  "--generate-pdf-document-outline",
  "--no-pings",
  "--ash-no-nudges",
  "--disable-infobars",
  '--simulate-outdated-no-au="Tue, 31 Dec 2099 23:59:59 GMT"',
  "--hide-crash-restore-bubble",
  "--suppress-message-center-popups",
  "--disable-domain-reliability",
  "--disable-datasaver-prompt",
  "--disable-speech-synthesis-api",
  "--disable-speech-api",
  "--disable-print-preview",
  "--safebrowsing-disable-auto-update",
  "--disable-external-intent-requests",
  "--disable-desktop-notifications",
  "--noerrdialogs",
  "--silent-debugger-extension-api",
  "--disable-extensions-http-throttling",
  "--extensions-on-chrome-urls",
  "--disable-default-apps",
  `--disable-features=${CHROME_DISABLED_COMPONENTS.join(",")}`,
];

export interface BuildChromeArgsOptions {
  headless?: boolean;
  docker?: boolean;
  disableSecurity?: boolean;
  remoteDebuggingPort: number;
  userDataDir: string;
  proxyServer?: string;
  proxyBypass?: string;
  userAgent?: string;
  acceptLanguage?: string;
  extensionPaths?: string[];
  extra?: string[];
}

export function buildChromeArgs(options: BuildChromeArgsOptions): string[] {
  const args = [
    `--remote-debugging-port=${options.remoteDebuggingPort}`,
    `--user-data-dir=${options.userDataDir}`,
    ...CHROME_DEFAULT_ARGS,
  ];

  if (options.headless) {
    args.push(...CHROME_HEADLESS_ARGS);
  }

  if (options.docker) {
    args.push(...CHROME_DOCKER_ARGS);
  }

  if (options.disableSecurity) {
    args.push(...CHROME_DISABLE_SECURITY_ARGS);
  }

  if (options.proxyServer) {
    args.push(`--proxy-server=${options.proxyServer}`);
    if (options.proxyBypass) {
      args.push(`--proxy-bypass-list=${options.proxyBypass}`);
    }
  }

  if (options.userAgent) {
    args.push(`--user-agent=${options.userAgent}`);
  }

  if (options.acceptLanguage) {
    args.push(`--lang=${options.acceptLanguage}`);
  }

  const extensionPaths = options.extensionPaths?.filter((value) => value.trim().length > 0) ?? [];
  if (extensionPaths.length > 0) {
    args.push("--enable-extensions");
    args.push("--disable-extensions-file-access-check");
    args.push(`--load-extension=${extensionPaths.join(",")}`);
  }

  if (options.extra) {
    args.push(...options.extra);
  }

  return args;
}
