import { Sparkles } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import type { StructuredProfile } from "@jobseeker/contracts";

import { PREFERENCE_SOURCE_LABELS } from "./types";

// Tier 3 — read-only AI output. Receded: muted panel, no card chrome, smaller
// type. Reads as "what the system concluded", not an input the user fills in.
export function InsightsTier({
  searchKeywords,
  discoveredPreferences,
  clarifications,
}: {
  searchKeywords: string[];
  discoveredPreferences: StructuredProfile["memory"]["discoveredPreferences"];
  clarifications: StructuredProfile["memory"]["clarifications"];
}) {
  return (
    <div className="space-y-8 rounded-xl bg-muted/30 p-6">
      <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
        <Sparkles className="size-3.5 text-violet-500" />
        Generated by AI from your resume and coach chat. Read-only.
      </div>

      <div className="space-y-3">
        <h3 className="text-sm font-medium">Search keywords</h3>
        {searchKeywords.length > 0 ? (
          <div className="flex flex-wrap gap-2">
            {searchKeywords.map((keyword) => (
              <Badge key={keyword} variant="secondary">
                {keyword}
              </Badge>
            ))}
          </div>
        ) : (
          <p className="text-xs text-muted-foreground">
            Keywords appear here after the profile is built.
          </p>
        )}
      </div>

      {discoveredPreferences.length > 0 ? (
        <div className="space-y-3">
          <h3 className="text-sm font-medium">Discovered preferences</h3>
          <div className="space-y-2">
            {discoveredPreferences.map((preference) => (
              <div
                key={`${preference.source}:${preference.preference}`}
                className="flex items-start gap-2 text-sm text-muted-foreground"
              >
                <Badge variant="outline" className="mt-0.5 shrink-0 font-normal">
                  {PREFERENCE_SOURCE_LABELS[preference.source] ?? preference.source}
                </Badge>
                <span>{preference.preference}</span>
              </div>
            ))}
          </div>
        </div>
      ) : null}

      {clarifications.length > 0 ? (
        <div className="space-y-3">
          <h3 className="text-sm font-medium">Remembered answers</h3>
          <div className="space-y-3">
            {clarifications.map((clarification) => (
              <div
                key={`${clarification.questionId}:${clarification.answeredAt}`}
                className="rounded-lg border bg-background/50 p-3"
              >
                <p className="text-sm font-medium">{clarification.question}</p>
                <p className="mt-1 text-sm text-muted-foreground">{clarification.answer}</p>
              </div>
            ))}
          </div>
        </div>
      ) : null}
    </div>
  );
}
